#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

# Shutdown
menuentry "System Shutdown" {
  echo "System shutting down..."
  halt
}

# Restart
menuentry "System Restart" {
  echo "Restarting System..."
  reboot
}

# UEFI Firmware
if [ ${grub_platform} == "efi" ]; then
	menuentry "Firmware Setup" {
	  fwsetup
	}
fi
